version: '{build}'

branches:
  # whitelist
  only:
    - master

environment:
  ARTIFACT_VERSION: 1.0.0
  repos_url:
    secure: wbMaKKMl/4jSAM/lB2wiESwbEs53q7vO8KO8QT/EdH6Tr3ZVtUxsYZSV7OpaYAPY
  repos_uid:
    secure: IYKu7Mmdx2GXqwxzp/IQNg==
  repos_pwd:
    secure: 2xpsiuGNHwFPtxdh8pA/Mm0I1bC1EfC8NBSoxOEiNco=

  matrix:
    - MY_NAME: Windows VS 2015 Debug 32bit
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VSINSTALL: "Microsoft Visual Studio 14.0\\VC"
      GYP_MSVS_VERSION: 2015
      MSVC_PLATFORM: x86
      BUILD_PLATFORM: Win32
      BUILD_CONFIGURATION: debug
      BUILD_ARCH: x86
      ARTIFACT_NAME: inac-breakpad-windows_vs15
      
    - MY_NAME: Windows VS 2015 Release 32bit
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VSINSTALL: "Microsoft Visual Studio 14.0\\VC"
      GYP_MSVS_VERSION: 2015
      MSVC_PLATFORM: x86
      BUILD_PLATFORM: Win32
      BUILD_CONFIGURATION: release
      BUILD_ARCH: x86
      ARTIFACT_NAME: inac-breakpad-windows_vs15
      
    - MY_NAME: Windows VS 2015 Debug 64bit
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VSINSTALL: "Microsoft Visual Studio 14.0\\VC"
      GYP_MSVS_VERSION: 2015
      MSVC_PLATFORM: amd64
      BUILD_PLATFORM: x64
      BUILD_CONFIGURATION: debug
      BUILD_ARCH: x86_x64
      ARTIFACT_NAME: inac-breakpad-windows_vs15
      
    - MY_NAME: Windows VS 2015 Release 64bit
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VSINSTALL: "Microsoft Visual Studio 14.0\\VC"
      GYP_MSVS_VERSION: 2015
      MSVC_PLATFORM: amd64
      BUILD_PLATFORM: x64
      BUILD_CONFIGURATION: release
      BUILD_ARCH: x86_x64
      ARTIFACT_NAME: inac-breakpad-windows_vs15

    - MY_NAME: Windows VS 2017 Debug 32bit
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VSINSTALL: "Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build"
      GYP_MSVS_VERSION: 2017
      MSVC_PLATFORM: x86
      BUILD_PLATFORM: Win32
      BUILD_CONFIGURATION: debug
      BUILD_ARCH: x86
      ARTIFACT_NAME: inac-breakpad-windows_vs17
      
    - MY_NAME: Windows VS 2017 Release 32bit
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VSINSTALL: "Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build"
      GYP_MSVS_VERSION: 2017
      MSVC_PLATFORM: x86
      BUILD_PLATFORM: Win32
      BUILD_CONFIGURATION: release
      BUILD_ARCH: x86
      ARTIFACT_NAME: inac-breakpad-windows_vs17

    - MY_NAME: Windows VS 2017 Debug 64bit
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VSINSTALL: "Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build"
      GYP_MSVS_VERSION: 2017
      MSVC_PLATFORM: amd64
      BUILD_PLATFORM: x64
      BUILD_CONFIGURATION: debug
      BUILD_ARCH: x86_64
      ARTIFACT_NAME: inac-breakpad-windows_vs17
      
    - MY_NAME: Windows VS 2017 Release 64bit
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VSINSTALL: "Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build"
      GYP_MSVS_VERSION: 2017
      MSVC_PLATFORM: amd64
      BUILD_PLATFORM: x64
      BUILD_CONFIGURATION: release
      BUILD_ARCH: x86_64
      ARTIFACT_NAME: inac-breakpad-windows_vs17
      
for:
-
  matrix:
    except:
      - image: Ubuntu
        
  clone_folder: c:\projects\breakpad\src

matrix:
    fast_finish: false

# Before checkout.
init:
  - cmd: |
         cd %APPVEYOR_BUILD_FOLDER%\..\..
         appveyor DownloadFile https://storage.googleapis.com/chrome-infra/depot_tools.zip
         7z -bd x depot_tools.zip -odepot_tools
         depot_tools\update_depot_tools
         cd %APPVEYOR_BUILD_FOLDER%

# After checkout.
install:
  - cmd: |
         PATH C:\projects\depot_tools;%PATH%
         cd %APPVEYOR_BUILD_FOLDER%\..
         gclient config https://%APPVEYOR_REPO_PROVIDER%.com/%APPVEYOR_REPO_NAME% --unmanaged --name=src
         gclient sync

build_script:
  - cmd: |
         cd %APPVEYOR_BUILD_FOLDER%
         msbuild src\client\windows\breakpad_client.sln /p:Configuration=%BUILD_CONFIGURATION% /p:Platform=%BUILD_PLATFORM% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /m /verbosity:normal
         msbuild src\tools\windows\tools_windows.sln    /p:Configuration=%BUILD_CONFIGURATION% /p:Platform=%BUILD_PLATFORM% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /m /verbosity:normal

after_build:
  - cmd: |
         cd %APPVEYOR_BUILD_FOLDER%
         C:\"Program Files (x86)"\"%VSINSTALL%"\vcvarsall.bat %MSVC_PLATFORM%
         mkdir dist
         mkdir dist\lib
         mkdir dist\include
         robocopy .\src\ .\dist\include *.h -S & exit 0
         lib /out:dist\lib\breakpad.lib src\client\windows\%BUILD_CONFIGURATION%\lib\common.lib src\client\windows\%BUILD_CONFIGURATION%\lib\crash_generation_client.lib src\client\windows\%BUILD_CONFIGURATION%\lib\exception_handler.lib
         cd dist
         7z a -mm=Deflate -r %ARTIFACT_NAME%-%BUILD_ARCH%-%BUILD_CONFIGURATION%-%ARTIFACT_VERSION%.zip *
         cd ..

artifacts:
  - path: dist/*.zip
    name: breakpad

deploy_script:
  - ps: |
        $src = $artifacts["breakpad"].path
        $artifact_name = Split-Path $src -leaf
        $artifact_name -match "(\d+\.\d+)"
        $artifact_version = $matches[1]
        $target = "inaos/breakpad/$artifact_version/$artifact_name"
        Write-Host $src
        Write-Host $artifact_name
        Write-Host $artifact_version
        Write-Host $target
        Write-Host $Env:OS
        $user = $env:repos_uid
        $pwd = $env:repos_pwd
        $url = "$env:repos_url/$target"
        if ($Env:OS -eq "Windows_NT") {
          Write-Host "curl.exe -u${user}:${pwd}  -T $src $url"
          $ret = curl.exe "-u${user}:${pwd}" "-T" $src $url 2>1
        } else {
          $ret = /usr/bin/curl "-u${user}:${pwd}" "-T" $src $url 2>1
        }
        $LastExitCode = 0
        
  
